layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

resume:
  - link: https://drive.google.com/file/d/1uxl5ax9vWj8P6BQ4mPOkSn3mrPjCHxHd/view?usp=sharing

social_media:
  website: https://goyalaryan.com
  linkedin: aryan-goyal
  stackoverflow: 13190250
  spotify: aryang2000
  instagram: aryan.gj
  # medium: your_username
  # facebook: your_username

experience:
  - name: Big Data Developer, DRVN Intelligence Inc. (Data Systems)
    description: Archtecting Big Data systems using GCP and Artifical Intelligence
    web_url: https://drvnintelligence.com/
    image_url: https://media-exp1.licdn.com/dms/image/C560BAQGdxBg2tWKxnQ/company-logo_200_200/0?e=2159024400&v=beta&t=EhHTVfAIoc6vldxAah4HiWNKw3jUDs8udzclgfHXNvY

  - name: Developer, RBC (Data & Analytics)
    description: Data Ontologies and Named Entity Recognition system using Natural Language Proccessing and Machine Learning
    web_url: https://www.rbc.com/about-rbc.html
    image_url: https://raw.githubusercontent.com/aryan-goyal/aryan-goyal.github.io/master/assets/rbc-dna.png
    
  - name: IT Advisory Board, University of Waterloo
    description: Implemented improvements to campus Wi-Fi services
    web_url: https://uwaterloo.ca/ist-advisory-board/
    image_url: https://upload.wikimedia.org/wikipedia/en/thumb/6/6e/University_of_Waterloo_seal.svg/1200px-University_of_Waterloo_seal.svg.png

  - name: Technical Systems Analyst, RBC (Global Techonology Infrastructure)
    description: Leveraged ML based Data Analytics systems in to detect operating system anomalies in datacenter.
    web_url: https://www.rbc.com/about-rbc.html
    image_url: https://lh3.googleusercontent.com/vY6CcG84EiozSiZwM1v1_UFEeOK2ADXlHWVV-vgl0qkF-dNcpTr-Mme7YpTPc0YtHoU

  - name: Software Analyst, Thales Canada (Transportation Solutions)
    description: Communication-Based Train Control (CBTC, Digital Signaling) metro projects in Hong Kong, Qatar, New York
    web_url: https://www.thalesgroup.com/en/americas/canada
    image_url: https://media-exp1.licdn.com/dms/image/C4D0BAQEmnUAXTuLkJQ/company-logo_200_200/0?e=2159024400&v=beta&t=gO3K5Eyewps-LALo509r2icge6ka0aqS5OfkgZEnuls

education:
  - name: Unviersity of Waterloo
    description: Bachelor of Applied Science (BASc), Computer Engieering (2017—2022)
    web_url: https://uwaterloo.ca/
    image_url: https://upload.wikimedia.org/wikipedia/en/thumb/6/6e/University_of_Waterloo_seal.svg/1200px-University_of_Waterloo_seal.svg.png

  - name: Sir Winston Churchill High School
    description: International Baccalaureate Diploma (2014—2017)
    web_url: http://school.cbe.ab.ca/school/sirwinstonchurchill/Pages/default.aspx
    image_url: https://photos.applyboard.com/schools/000/000/450/logos/original/Sir_Winston_Churchill_LOGO.png?1542310856

  - name: Thomas Jefferson High School for Science and Technology 
    description: (2013)
    web_url: https://tjhsst.fcps.edu/
    image_url: https://upload.wikimedia.org/wikipedia/en/b/b4/Tjlogo.png

topics:
  - name: Scala
    web_url: https://github.com/topics/scala
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/scala/scala.png

  - name: Machine Learning 
    web_url: https://github.com/topics/machine-learning
    image_url: https://i.pinimg.com/originals/a2/aa/45/a2aa45502770db5ee345064f63fdb7af.png

  - name: System Design
    web_url: https://github.com/topics/system-design
    image_url: https://images.squarespace-cdn.com/content/v1/5704eafe3c44d8b8f6665c04/1507492007792-7GAKSHYNEB5A7WPDGTJC/ke17ZwdGBToddI8pDm48kKGNYk_wTTMfXZ6qjLA49-BZw-zPPgdn4jUwVcJE1ZvWEtT5uBSRWt4vQZAgTJucoTqqXjS3CfNDSuuf31e0tVH2ATtxt8VnPebSpV9kfvvu2LNCOGf3YgcgSBGMuxXv9e87Nsj43NRAr6WuWZv5DKs/adrien-harrison-echo-studio-system-idea-generation.png